# Site settings
title: About Björn Engel
description: About Björn Engel
url: "https://engel-b.github.io"

# User settings
username: Björn Engel
user_description:  I'm a creative thinker and like to explore alternative solutions to problems and have an open mind about what will work best. I like solving problems and coming up with solutions in a timely manner. I thrive in team settings, and I think my ability to effectively communicate with others is what drives my ability to solve a variety of problems.<br><br>While working fulltime, I am also father and a spare time hobbyist in  homeautomation.
user_title: Software Engineer
email: contact.engel.b@gmail.com
xing_profile: Bjoern_Engel7
github_username: engel-b

# Google-analytics
google-analytics:
  id: "UA-116291357-1"

exclude: ['package.json', 'src' , 'node_modules']
