# Site settings
title: About Bj&ouml;rn Engel
description: About Bj&ouml;rn Engel
url: "https://justcoke.github.io"

# User settings
username: Bj&ouml;rn Engel
user_description: Software Engineer and Father
user_title: Software Engineer
email: 
xing_profile: Bjoern_Engel7
github_username: justcoke

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
