# Site settings
title: About Bj&ouml;rn Engel
description: About Bj&ouml;rn Engel
url: "https://justcoke.github.io"

# User settings
username: Bj&ouml;rn Engel
user_description:  I'm a creative thinker and like to explore alternative solutions to problems and have an open mind about what will work best. I like solving problems and coming up with solutions in a timely manner. I thrive in team settings, and I think my ability to effectively communicate with others is what drives my ability to solve a variety of problems.<br><br>While working fulltime, I am also father and a spare time hobbyist in  homeautomation.
user_title: Software Engineer
email: contact.justcoke@gmail.com
xing_profile: Bjoern_Engel7
github_username: justcoke

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
